# Generated by Django 5.2 on 2025-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("patronymic_name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serial_number", models.CharField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=2000)),
                ("genre", models.CharField(max_length=255)),
                ("language", models.CharField(choices=[("eng", "Английский"), ("ru", "Русский")])),
                ("publishing_house", models.CharField(max_length=255)),
                ("place_of_publication", models.CharField(max_length=50)),
                ("publication_year", models.PositiveIntegerField(max_length=4)),
                ("author", models.ManyToManyField(to="books.author")),
            ],
        ),
    ]
