# Generated by Django 5.2 on 2025-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_receipt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(choices=[("eng", "Английский"), ("ru", "Русский")], max_length=10),
        ),
        migrations.AlterField(
            model_name="book",
            name="receipt_status",
            field=models.CharField(
                choices=[("free", "Доступна для выдачи"), ("on_hands", "Выдана на руки")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="serial_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
