# Generated by Django 5.2 on 2025-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="patronymic_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="place_of_publication",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishing_house",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
