# Generated by Django 5.2 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_book", "0002_alter_receiptbook_period_in_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptbook",
            name="period_in_days",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
