# Generated by Django 5.2 on 2025-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_book", "0003_alter_receiptbook_period_in_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptbook",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
