# Generated by Django 5.2 on 2025-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_author_description_and_more"),
        ("receipt_book", "0004_alter_receiptbook_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptbook",
            name="book",
            field=models.ForeignKey(on_delete=models.SET(0), to="books.book"),
        ),
    ]
